// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dktlwtnfevdxfsudikia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrdGx3dG5mZXZkeGZzdWRpa2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Njk0NTIsImV4cCI6MjA2NDI0NTQ1Mn0.WVphVMJ3eDq-KN37i0t9F2NZbNlt9BKHCqMHPaeU6CM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);